name: Publish Wynn Kit

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Get current and previous versions
        id: versions
        run: |
          echo "🔍 Reading package version..."
          NEW_VERSION=$(jq -r .version package.json)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          git fetch --depth=2 origin ${{ github.ref }}
          PREV_VERSION=$(git show HEAD^:package.json | jq -r .version || echo "none")
          echo "prev_version=$PREV_VERSION" >> $GITHUB_OUTPUT

          echo "🆕 New version: $NEW_VERSION"
          echo "⬅️ Previous version: $PREV_VERSION"

      - name: Skip if version did not change
        if: steps.versions.outputs.prev_version == steps.versions.outputs.new_version
        run: |
          echo "⚠️ Version has not changed. Skipping publish."
          exit 0

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
